import { describe, expect, it } from 'vitest'
import { avatarInitials, canShowOnCard, detectProviderFromUrl, hasValidDestination, isDemoUsername, isHexColor, isProfileComplete, levelFromXp, normalizeProviderUrl, parseProviderInput, publicSearchHref, safeUrlSchema, tapHomeRoute, usernameSchema } from './core'
import { demoConnections, demoProfile, emptyProfile } from '../data/demo'
import { filterProviders, mainProviderIds, providers } from './providers'
import { canRefreshAt, cooldownLabel, earnedMilestones, revealDelay, shouldAnimateReveal, snapshotRows, verifiedXpSummary } from './verifiedStats'

describe('critical profile logic',()=>{
  it('validates canonical usernames',()=>{expect(usernameSchema.parse('Pixel_King')).toBe('pixel_king');expect(()=>usernameSchema.parse('ad min')).toThrow();expect(()=>usernameSchema.parse('admin')).toThrow()})
  it('rejects unsafe URLs',()=>{expect(safeUrlSchema.parse('https://example.com')).toContain('https');expect(()=>safeUrlSchema.parse('javascript:alert(1)')).toThrow();expect(()=>safeUrlSchema.parse('http://example.com')).toThrow()})
  it('normalizes provider handles',()=>{expect(normalizeProviderUrl('instagram','@example')).toBe('https://instagram.com/example');expect(normalizeProviderUrl('tiktok','@example')).toBe('https://tiktok.com/@example');expect(normalizeProviderUrl('github','https://github.com/example')).toContain('github.com/example');expect(normalizeProviderUrl('discord','example')).toBe('')})
  it('calculates deterministic levels',()=>{expect(levelFromXp(0).level).toBe(1);expect(levelFromXp(740)).toMatchObject({level:3,current:340,required:500})})
  it('shows only selected visible connections',()=>{expect(canShowOnCard('a',['a'],true)).toBe(true);expect(canShowOnCard('a',['a'],false)).toBe(false);expect(canShowOnCard('a',['b'],true)).toBe(false)})
  it('guards profile completion and destinations',()=>{expect(isProfileComplete({username:'example',displayName:'Example',onboardingComplete:true})).toBe(true);expect(isProfileComplete({username:'',displayName:'',onboardingComplete:false})).toBe(false);expect(hasValidDestination('https://github.com/example')).toBe(true);expect(hasValidDestination('')).toBe(false)})
  it('validates six digit hex colors',()=>{expect(isHexColor('#8B5CF6')).toBe(true);expect(isHexColor('#bad')).toBe(false);expect(isHexColor('red')).toBe(false)})
  it('detects and parses supported profile links',()=>{expect(detectProviderFromUrl('https://instagram.com/popkornys/')).toBe('instagram');expect(parseProviderInput('youtube','https://youtube.com/@example')).toMatchObject({handle:'example',url:'https://youtube.com/@example'});expect(()=>parseProviderInput('github','https://instagram.com/example')).toThrow()})
  it('accepts scheme-less profiles and rejects content, settings and lookalike domains',()=>{expect(parseProviderInput('instagram','instagram.com/user')).toMatchObject({handle:'user',url:'https://instagram.com/user'});expect(()=>parseProviderInput('github','https://github.com/settings')).toThrow();expect(()=>parseProviderInput('instagram','https://instagram.com/p/abc')).toThrow();expect(()=>parseProviderInput('youtube','https://youtube.com/watch?v=abc')).toThrow();expect(()=>parseProviderInput('github','https://evil.example/user')).toThrow()})
  it('rejects unintended URL schemes for provider input',()=>{for(const value of ['javascript:alert(1)','data:text/html,hi','vbscript:msgbox(1)','file:///etc/passwd','http://github.com/user'])expect(()=>parseProviderInput('github',value)).toThrow()})
  it('creates consistent avatar initials',()=>{expect(avatarInitials('John Smith')).toBe('JS');expect(avatarInitials('Popkornys')).toBe('PO');expect(avatarInitials('')).toBe('?')})
  it('keeps showcase data isolated from empty real profiles',()=>{expect(demoProfile.username).toBe('example');expect(demoConnections.length).toBeGreaterThanOrEqual(10);expect(emptyProfile.username).toBe('');expect(emptyProfile.onboardingComplete).toBe(false)})
  it('keeps the showcase non-navigable and database-reserved',()=>{expect(isDemoUsername('Example')).toBe(true);expect(demoConnections.every(connection=>connection.profileUrl==='')).toBe(true);expect(()=>usernameSchema.parse('example')).toThrow()})
  it('shapes private search results as non-navigable',()=>{expect(publicSearchHref({username:'private-user',isPrivate:true})).toBeUndefined();expect(publicSearchHref({username:'public-user',isPrivate:false})).toBe('/u/public-user')})
  it('routes the TAP logo from the resolved auth state',()=>{expect(tapHomeRoute({realMode:true,ready:true,authenticated:true,complete:true})).toBe('/app');expect(tapHomeRoute({realMode:true,ready:true,authenticated:true,complete:false})).toBe('/onboarding');expect(tapHomeRoute({realMode:true,ready:true,authenticated:false,complete:false})).toBe('/')})
  it('keeps the existing catalog featured while every category can search extended apps',()=>{expect(filterProviders('').every(provider=>mainProviderIds.has(provider.id))).toBe(true);expect(filterProviders('LinkedIn','social').map(provider=>provider.id)).toContain('linkedin');expect(filterProviders('Battle','gaming').map(provider=>provider.id)).toContain('battlenet');expect(filterProviders('LeetCode','developer').map(provider=>provider.id)).toContain('leetcode');expect(providers.length).toBeGreaterThan(85)})
  it('assigns complete provider capability metadata and verified candidates',()=>{expect(providers.every(provider=>provider.tier&&provider.readiness&&provider.supportedMetricKeys)).toBe(true);expect(providers.find(provider=>provider.id==='github')).toMatchObject({tier:'A',supportsVerifiedStats:true,supportsRefresh:true});expect(providers.find(provider=>provider.id==='custom')?.tier).toBe('E')})
  it('awards verified XP milestones once',()=>{const first=earnedMilestones('github','followers',120);expect(first.map(item=>item.key)).toEqual(['10','100']);const repeated=earnedMilestones('github','followers',120,first.map(item=>item.awardKey));expect(repeated).toEqual([]);expect(earnedMilestones('github','followers',1200,first.map(item=>item.awardKey)).map(item=>item.key)).toEqual(['1k'])})
  it('calculates verified XP summaries safely',()=>{expect(verifiedXpSummary(1000,760)).toEqual({totalXp:1000,verifiedXp:760,verifiedPercent:76});expect(verifiedXpSummary(0,500).verifiedXp).toBe(0)})
  it('builds snapshot rows and enforces cooldown timing',()=>{const rows=snapshotRows([{connectionId:'c1',providerId:'github',metricKey:'stars',metricValue:42}],'2026-01-01T00:00:00.000Z');expect(rows[0]).toMatchObject({provider_id:'github',metric_key:'stars',metric_value:42});expect(canRefreshAt('2026-01-01T01:00:00.000Z',new Date('2026-01-01T00:00:00.000Z').getTime())).toBe(false);expect(cooldownLabel('2026-01-01T00:42:00.000Z',new Date('2026-01-01T00:00:00.000Z').getTime())).toContain('42 minutes')})
  it('uses bounded reveal staggering and disables it for reduced motion',()=>{expect(revealDelay(3)).toBe(135);expect(revealDelay(99)).toBe(360);expect(revealDelay(3,true)).toBe(0);expect(shouldAnimateReveal(false,false)).toBe(true);expect(shouldAnimateReveal(false,true)).toBe(false)})
})
